integration:
  weatherstack:
    base-url: http://api.weatherstack.com
    access-key: ${WEATHERSTACK_ACCESS_KEY}

  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      name: ${TELEGRAM_BOT_NAME}